### PR TITLE
New Mekkablue Plugins - Show Italics & Show Tops And Bottoms

### PR DESCRIPTION
**Pull request by drawcard**
Added 2 new useful repos to the collection per #5

### CODE REVIEW

**Comment by zar-nicolas20** [comment]
It seem that there is a conflict, I will clean up the bash shell. Also I am adding other repositories, thanks

**Comment by drawcard** [comment]
Ok thanks, I'll let you handle it :)

**Comment by zar-nicolas20** [comment]
Good job with this integrations. I am solving a conflict in the file but I have preserve your lines.

**Comment by zar-nicolas20** [comment]
The conflict was solved doing a new commit,

**Comment by drawcard** [comment]
No worries, glad I can help - I also had a thought that you might find it easier to [use loops](http://www.cyberciti.biz/faq/bash-for-loop-array/) in the config script to keep the repetition level down and make it easier to add new scripts and plugins - you could store the github URL's in an array, and run them through a loop to fetch each one. It's probably something you're working on but I thought I'd suggest it anyhow! If you want me to have a shot at it too, let me know!

**Comment by zar-nicolas20** [comment]
Yes, That is very useful.

I think that is the best option to make easier the addition of new data.

Thanks for collaborating with this bash script.

Best,

Nicolás

**Comment by drawcard** [comment]
No problem, this script is a great idea and I'm happy to help making it better for all!

**Comment by zar-nicolas20** [comment]
👍 Nice!

**Pull request closed without merging**
